# Generated by Django 5.0.1 on 2025-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_created_at_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
