# Generated by Django 5.0.1 on 2025-10-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_telegram_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='api.preacher'),
        ),
    ]
