# Generated by Django 5.0.1 on 2025-10-28 04:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sermon_preacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_audio',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
