# Generated by Django 5.0.1 on 2025-10-29 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_telegram_audio_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='preacher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date_uploaded'], 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AlterModelOptions(
            name='telegram_audio',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Telegram Audio', 'verbose_name_plural': 'Telegram Audios'},
        ),
        migrations.AlterField(
            model_name='sermon',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_note', to='api.note'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sermons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegram_audio',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_audios', to=settings.AUTH_USER_MODEL),
        ),
    ]
